"""Change image_urls to image_url in posts table

Revision ID: 3cb2bac5f8a7
Revises: b70fdfd17a1b
Create Date: 2025-12-19 17:08:35.470090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cb2bac5f8a7'
down_revision: Union[str, Sequence[str], None] = 'b70fdfd17a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_column('posts', 'image_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
