"""Update workspace model with new attributes

Revision ID: 510da67b0617
Revises: 1ddfda221d96
Create Date: 2025-12-24 12:39:23.319647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510da67b0617'
down_revision: Union[str, Sequence[str], None] = '1ddfda221d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new columns first (name as nullable initially)
    op.add_column('workspaces', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('type', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Migrate data: copy business_name to name
    op.execute("UPDATE workspaces SET name = COALESCE(business_name, 'Unnamed Workspace')")
    
    # Now make name NOT NULL
    op.alter_column('workspaces', 'name', nullable=False)
    
    # Drop old columns
    op.drop_index(op.f('ix_workspaces_business_name'), table_name='workspaces')
    op.drop_column('workspaces', 'business_name')
    op.drop_column('workspaces', 'default_tone')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('default_tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('business_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_workspaces_business_name'), 'workspaces', ['business_name'], unique=False)
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'created_at')
    op.drop_column('workspaces', 'address')
    op.drop_column('workspaces', 'description')
    op.drop_column('workspaces', 'type')
    op.drop_column('workspaces', 'name')
    # ### end Alembic commands ###
