"""Replace is_scheduled with status field in posts table

Revision ID: 5bd155123caa
Revises: a557af045005
Create Date: 2025-12-22 11:22:18.956404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd155123caa'
down_revision: Union[str, Sequence[str], None] = 'a557af045005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add status column with default value first
    op.add_column('posts', sa.Column('status', sa.String(length=50), nullable=False, server_default='draft'))
    
    # Migrate existing data: is_scheduled=1 -> 'scheduled', is_scheduled=0 -> 'published'
    op.execute("UPDATE posts SET status = 'scheduled' WHERE is_scheduled = 1")
    op.execute("UPDATE posts SET status = 'published' WHERE is_scheduled = 0 OR is_scheduled IS NULL")
    
    # Remove the default after migration
    op.alter_column('posts', 'status', server_default=None)
    
    # Drop old column
    op.drop_column('posts', 'is_scheduled')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_scheduled', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
