"""Add page_accounts table for Facebook and Instagram pages

Revision ID: 9b90864f94df
Revises: f53a1a8728e3
Create Date: 2025-12-18 16:07:41.568192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b90864f94df'
down_revision: Union[str, Sequence[str], None] = 'f53a1a8728e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=255), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('page_access_token', sa.Text(), nullable=False),
    sa.Column('instagram_account_id', sa.String(length=255), nullable=True),
    sa.Column('instagram_username', sa.String(length=255), nullable=True),
    sa.Column('can_post_to_facebook', sa.Boolean(), nullable=False),
    sa.Column('can_post_to_instagram', sa.Boolean(), nullable=False),
    sa.Column('is_selected_for_facebook', sa.Boolean(), nullable=False),
    sa.Column('is_selected_for_instagram', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_accounts_id'), 'page_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_page_accounts_page_id'), 'page_accounts', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_accounts_page_id'), table_name='page_accounts')
    op.drop_index(op.f('ix_page_accounts_id'), table_name='page_accounts')
    op.drop_table('page_accounts')
    # ### end Alembic commands ###
