"""Add platform_content and platform_image_url to post_platforms

Revision ID: a557af045005
Revises: 3cb2bac5f8a7
Create Date: 2025-12-22 10:23:49.362413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a557af045005'
down_revision: Union[str, Sequence[str], None] = '3cb2bac5f8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_platforms', sa.Column('platform_content', sa.Text(), nullable=True))
    op.add_column('post_platforms', sa.Column('platform_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_platforms', 'platform_image_url')
    op.drop_column('post_platforms', 'platform_content')
    # ### end Alembic commands ###
