"""Add topic tone hashtag fields to posts table

Revision ID: ab4fdc66e332
Revises: 5bd155123caa
Create Date: 2025-12-23 10:00:29.504477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4fdc66e332'
down_revision: Union[str, Sequence[str], None] = '5bd155123caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('topic', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('tone', sa.String(length=100), nullable=True))
    op.add_column('posts', sa.Column('hashtag', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'hashtag')
    op.drop_column('posts', 'tone')
    op.drop_column('posts', 'topic')
    # ### end Alembic commands ###
