"""Add scheduled_at and is_scheduled to posts table

Revision ID: b70fdfd17a1b
Revises: 0fc433cae4da
Create Date: 2025-12-19 16:36:30.824268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70fdfd17a1b'
down_revision: Union[str, Sequence[str], None] = '0fc433cae4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('is_scheduled', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_scheduled')
    op.drop_column('posts', 'scheduled_at')
    # ### end Alembic commands ###
