"""Remove content and image_url from posts table

Revision ID: c9739cbbcd8a
Revises: ab4fdc66e332
Create Date: 2025-12-24 12:05:19.982616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9739cbbcd8a'
down_revision: Union[str, Sequence[str], None] = 'ab4fdc66e332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_url')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
